# tools/test-rules-sweep.ps1 - assert that every implemented preflight code fires.
#
# The fixture is generated by tools/make-bad-sheets.py and deliberately breaks one
# rule per file. A rule listed here that does not appear in the report is either
# broken or has a fixture that does not actually trigger it - both are defects.
#
# This exists because "every firing rule proven by a committed test" was an
# overstatement when written: only a handful of codes were asserted, and
# E-SCHEMA-DRIFT had never fired at all.
#
# Exit 0 = every listed code fired. Exit 1 = at least one did not.
#
# The engine is built (or refused) by tools/engine.ps1 before anything is asserted,
# so a stale target/debug/sheetty.exe cannot make this pass by exercising rules
# that no longer exist in the tree.
#
# A Restricted execution policy kills `powershell -File tools/test-rules-sweep.ps1`
# before the first line runs; use the launcher instead:
#
#     python tools/ps.py tools/test-rules-sweep.ps1

$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)
. (Join-Path $PSScriptRoot "engine.ps1")

if (-not (Test-Path "tests/sweep/sheets")) {
    Write-Host "generating fixtures..."
    python tools/make-bad-sheets.py
    if ($LASTEXITCODE -ne 0) { throw "tools/make-bad-sheets.py failed; the sweep fixture is not there" }
}

# A sweep is only as good as the bytes it is run against. E-L0-EOL is proved by
# crlf.tsv holding a real CR, and canonical form (preflight check 2) requires every
# other fixture to hold none. A checkout can silently destroy both, and the failure
# then looks like a broken RULE rather than a broken fixture:
#   - the committed tests/sweep/sheets/crlf.tsv blob is LF, so its -text attribute
#     cannot restore the CR until the file is re-added - with the documented
#     core.autocrlf=input the sweep then reports "E-L0-EOL did not fire";
#   - with core.autocrlf=true (the Git-for-Windows default, which is not cloned)
#     every OTHER fixture comes out CRLF, so E-L0-EOL fires on files that are not
#     its fixture and the sweep passes for the wrong reason.
# Assert the preconditions loudly instead of trusting the checkout.
$fixtureDir = "tests/sweep/sheets"
$crlfFixture = Join-Path $fixtureDir "crlf.tsv"
if (-not (Test-Path $crlfFixture)) { throw "missing fixture $crlfFixture" }
if (-not ([System.IO.File]::ReadAllBytes($crlfFixture) -contains 13)) {
    throw ("$crlfFixture holds no CR, so the E-L0-EOL fixture is inert and this sweep proves nothing. " +
           "The committed blob is LF; restore the file's CRLF bytes (its -text rule in .gitattributes " +
           "keeps them once the blob holds them) before trusting this result.")
}
$rewritten = @()
foreach ($f in (Get-ChildItem $fixtureDir -Recurse -File -Filter *.tsv)) {
    if ($f.Name -eq "crlf.tsv") { continue }
    if ([System.IO.File]::ReadAllBytes($f.FullName) -contains 13) { $rewritten += $f.Name }
}
if ($rewritten.Count -gt 0) {
    throw ("{0} fixture(s) hold CR, which canonical form forbids: {1}. The checkout rewrote them, so " -f `
           $rewritten.Count, ($rewritten -join ", ")) +
           "E-L0-EOL would fire on the wrong files. Set core.autocrlf=input (or pin '*.tsv text eol=lf' " +
           "in .gitattributes before its -text rules) before trusting this sweep."
}

$exe = Get-SheettyExe

$json = $null
try {
    # The E-L0-GENERATED probe is created here rather than committed. The rule
    # scans outward from the sheets directory, so a persisted banner file would
    # make the REAL book fail preflight - correctly, since D6 forbids a generated
    # file in the working tree.
    $probe = "tests/sweep/_generated_probe.rs"
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) $probe),
        "// GENERATED BY sheetty v0.1.0 FROM probe - DO NOT EDIT`n",
        (New-Object System.Text.UTF8Encoding($false)))

    $json = & $exe preflight --sheets tests/sweep/sheets --json 2>&1 | Out-String
}
finally {
    if (Test-Path "tests/sweep/_generated_probe.rs") { Remove-Item "tests/sweep/_generated_probe.rs" -Force }
}

# Parse the JSON report rather than grepping the human one. This is not a
# stylistic choice: the human report truncates at 12 findings per layer, so
# grepping it produced 14 false "did not fire" results against a fixture with
# 124 errors. A test harness must not depend on a display convenience.
try {
    $rep = $json | ConvertFrom-Json
} catch {
    Write-Host "could not parse the JSON report" -ForegroundColor Red
    Write-Host $json
    exit 1
}
$found = @{}
foreach ($f in $rep.findings) { $found[$f.code] = $f.severity }
Write-Host ("report: {0} sheets, {1} rows, {2} errors, {3} warnings, {4} distinct codes" -f `
    $rep.sheets, $rep.rows, $rep.errors, $rep.warnings, $found.Count)
Write-Host ""

# Every code this engine can emit.
#   E-L0-IO       needs an unreadable file: a filesystem condition, not a fixture.
#   E-L0-NOSCHEMA requires the *absence* of 01-schema.tsv, which is mutually
#                 exclusive with the E-SCHEMA-DRIFT fixtures in this directory.
#                 It is asserted by tools/test-preflight.ps1 instead, whose
#                 fixture deliberately has no schema sheet.
$expected = @(
    "E-L0-BOM", "E-L0-EOL", "E-L0-ENC", "E-L0-DELIM", "E-L0-HEADER", "E-L0-NOHEADER",
    "E-L0-MANIFEST", "E-L0-EMITTER", "E-L0-KEY", "E-L0-CHARSET", "E-L0-DUPKEY",
    "E-L0-WIDE", "E-L0-KERNEL", "E-L0-GENERATED",
    "E-L1-TYPE", "E-L1-VALUE", "E-L1-EMPTY", "E-L1-UNIT", "E-L1-DEFAULT",
    "W-L1-QUOTED", "W-L0-SHORT",
    "E-L2-REF", "E-L2-NOEVIDENCE", "E-L2-CYCLE", "E-L2-TOPO",
    "E-SCHEMA-DRIFT", "E-SCHEMA-EXTRA", "E-SCHEMA-MISSING",
    "E-L5-DIVERGE",
    "E-L6-BUDGET", "W-L6-VIEW"
)

$missing = @()
foreach ($code in $expected) {
    if ($found.ContainsKey($code)) {
        Write-Host ("  ok   {0,-20} {1}" -f $code, $found[$code])
    } else {
        Write-Host ("  FAIL {0,-20} did not fire" -f $code) -ForegroundColor Red
        $missing += $code
    }
}

Write-Host ""
if ($missing.Count -gt 0) {
    Write-Host ("FAILED: {0} of {1} codes did not fire: {2}" -f $missing.Count, $expected.Count, ($missing -join ", ")) -ForegroundColor Red
    exit 1
}
Write-Host ("PASSED: all {0} preflight codes fired against the sweep fixture." -f $expected.Count)
exit 0
